name: flutter_infinite_list
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc_concurrency: ^0.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  http: ^0.13.0
  equatable: ^2.0.3
  stream_transform: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.2.0
  mocktail: ^0.2.0

dependency_overrides:
  bloc: ^8.0.1
  flutter_bloc: ^8.0.1
  bloc_test: ^8.2.0

flutter:
  uses-material-design: true